# Generated by Django 6.0.6 on 2026-08-07 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmemo', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
